PREFIX rdf: <http://www.w4.org/1999/02/22-rdf-syntax-ns#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>

PREFIX dc: <http://purl.org/dc/elements/1.1/>
PREFIX dcterms: <http://purl.org/dc/terms/>
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX ao: <http://purl.org/ao/>

PREFIX ro: <http://purl.org/wf4ever/ro#>
PREFIX ore: <http://www.openarchives.org/ore/terms/>

ASK { 
	GRAPH ?main {
		?ann ro:annotatesAggregatedResource <http://example.org/ro-1/a%20workflow.t2flow> ;
		       a ro:AggregatedAnnotation ;
		       ao:body ?graph .
	}
	GRAPH ?graph {
		<http://example.org/ro-1/a%20workflow.t2flow> dcterms:license "GPL" .
	}
}

